
services:

  user-home-backend:
    build:
      context: ./User-Home-Service/Backend/
    ports:
      - "4002:4002"
  user-home-frontend:
    build:
      context: ./User-Home-Service/Frontend/
    ports:
      - "4003:4003"
  user-auth-backend:
    build:
      context: ./User-Auth-Service/Backend/
    ports:
      - "4000:4000"
  user-auth-frontend:
    build:
      context: ./User-Auth-Service/Frontend/
    ports:
      - "4001:4001"


networks:
  default:
    driver: bridge
